import {
  AGENT_AND_SKILL_MATRIX_BLOCK,
  CANONICAL_RETURN_ENVELOPE_BLOCK,
  DELEGATION_DECISION_BLOCK,
  DIRECT_MUTATIONS_BLOCK,
  DISPATCH_CONTRACT_BLOCK,
  FINITE_HITL_DESIGN_PIPELINE_BLOCK,
  IDENTITY_AND_AUTHORITY_BLOCK,
  JEV_JUDGMENT_BLOCK,
  ORCHESTRATOR_AGENT_ROUTING_BLOCK,
  TERMINAL_STATES_BLOCK,
  WORKFLOW_RULES_BLOCK,
  WORKTREE_RULES_BLOCK,
} from "./orchestrator-shared-blocks.js";

const ORCHESTRATE_HEAD = `You are the ARCS orchestrator. Dispatch, don't implement.

${IDENTITY_AND_AUTHORITY_BLOCK}

${WORKFLOW_RULES_BLOCK}

${ORCHESTRATOR_AGENT_ROUTING_BLOCK}

${DELEGATION_DECISION_BLOCK}

${DISPATCH_CONTRACT_BLOCK}

${WORKTREE_RULES_BLOCK}

${AGENT_AND_SKILL_MATRIX_BLOCK}

${FINITE_HITL_DESIGN_PIPELINE_BLOCK}

${DIRECT_MUTATIONS_BLOCK}`;

const ORCHESTRATE_TAIL = `${CANONICAL_RETURN_ENVELOPE_BLOCK}

${TERMINAL_STATES_BLOCK}`;

/** Canonical orchestrator flow without the JeV policy; the terse caveman overlay supplies its own form. */
export const ORCHESTRATE_PROMPT_BODY = `${ORCHESTRATE_HEAD}

${ORCHESTRATE_TAIL}`;

export const ORCHESTRATE_PROMPT_TEXT = `${ORCHESTRATE_HEAD}

${JEV_JUDGMENT_BLOCK}

${ORCHESTRATE_TAIL}`;
