/**
 * Shared storage utilities for ARCS project stores.
 *
 * Filesystem helpers, validation utilities, and common types used by
 * plan-store, knowledge-store, and task-store modules.
 */

import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { access, mkdir, open, readFile, rename, rm, unlink } from "node:fs/promises";
import { dirname } from "node:path";
import {
  invalidFileRef,
  invalidKeyword,
  invalidKnowledgeKind,
  invalidPlanStatus,
  invalidSessionLink,
  invalidSessionRuntimeType,
  invalidSessionStatus,
  invalidTaskPriority,
  invalidTaskStatus,
} from "./errors.js";

// ---------------------------------------------------------------------------
// Enums — Plans
// ---------------------------------------------------------------------------

export const PLAN_STATUSES = [
  "proposed",
  "planned",
  "in_progress",
  "blocked",
  "done",
  "archived",
] as const;

export type PlanStatus = (typeof PLAN_STATUSES)[number];

export const KNOWLEDGE_KINDS = [
  "lesson",
  "gotcha",
  "pattern",
  "architecture",
  "module",
  "feature",
  "reference",
  "decision",
] as const;

export type KnowledgeKind = (typeof KNOWLEDGE_KINDS)[number];

export const KNOWLEDGE_AUDIENCES = [
  "orchestrator",
  "implementer",
  "designer",
  "universal",
] as const;

export type KnowledgeAudience = (typeof KNOWLEDGE_AUDIENCES)[number];

// ---------------------------------------------------------------------------
// Enums — Tasks
// ---------------------------------------------------------------------------

export const TASK_STATUSES = ["backlog", "in_progress", "done", "cancelled"] as const;
export type TaskStatus = (typeof TASK_STATUSES)[number];

export const TASK_PRIORITIES = ["critical", "high", "medium", "low"] as const;
export type TaskPriority = (typeof TASK_PRIORITIES)[number];

// ---------------------------------------------------------------------------
// Enums — Sessions
// ---------------------------------------------------------------------------

export const SESSION_STATUSES = ["active", "idle", "completed", "failed", "disconnected"] as const;
export type SessionStatus = (typeof SESSION_STATUSES)[number];

export const SESSION_RUNTIME_TYPES = ["claude-code", "opencode", "pi", "codex"] as const;
export type SessionRuntimeType = (typeof SESSION_RUNTIME_TYPES)[number];

/**
 * DAG node kinds a session may be linked to. Linkage always keys on the
 * task/plan normalized id — never on a diagram node id (T001…), which is
 * regenerated by `arcs diagram sort-metadata`.
 */
export const SESSION_LINKED_NODE_TYPES = ["task", "plan"] as const;
export type SessionLinkedNodeType = (typeof SESSION_LINKED_NODE_TYPES)[number];

// ---------------------------------------------------------------------------
// FileRef type
// ---------------------------------------------------------------------------

export interface FileRef {
  path: string;
  anchor?: string;
  /**
   * Optional 1-indexed line range, carried through from a proposal or a
   * `--source-files`-style ref so a code chunk can be captured deterministically.
   * Present only as a pair with `endLine`.
   */
  startLine?: number;
  endLine?: number;
}

/**
 * A line range in a workspace file. Mirrors the `file` reference vocabulary
 * used by the ask route (`path` + `startLine` + `endLine`). Paths containing
 * Windows drive letters or colons are out of scope for `parseCodeRef`.
 */
export interface CodeRef {
  path: string;
  startLine: number;
  endLine: number;
  anchor?: string;
}

/**
 * A captured slice of a workspace file: the range plus the text lifted from it
 * at capture time. `headRev`/`capturedAt` are supplied by the caller (the
 * caller owns git); this module never shells out.
 */
export interface CodeChunk {
  path: string;
  startLine: number;
  endLine: number;
  language?: string;
  snippet: string;
  anchor?: string;
  headRev?: string;
  capturedAt: string;
}

/**
 * Validates and normalizes an array of FileRef objects.
 * - path: backslashes normalized to forward slashes first, then validated.
 *   Must be relative (no leading /), no .., no empty, no #, comma, or colon.
 * - anchor: if provided, must be non-empty/non-whitespace, no # or comma.
 * - startLine/endLine: optional 1-indexed range; must be supplied together and
 *   satisfy 1 <= startLine <= endLine. Carried through verbatim when valid.
 * Returns a new array with normalized paths. Throws on invalid input.
 */
export function sanitizeFileRefs(refs: FileRef[]): FileRef[] {
  return refs.map((ref) => {
    // Normalize backslashes to forward slashes first (Windows path compat)
    const path = ref.path.replace(/\\/g, "/").replace(/\/+$/, "");
    if (!path?.trim()) {
      throw invalidFileRef("path must not be empty");
    }
    if (path.startsWith("/")) {
      throw invalidFileRef(`path must be relative, got "${path}"`);
    }
    if (/(^|\/)\.\.($|\/)/.test(path)) {
      throw invalidFileRef(`path must not contain ".." segments, got "${path}"`);
    }
    // Note: backslash already normalized above, so only check #, comma, colon
    if (/[#,:]/.test(path)) {
      throw invalidFileRef(`path must not contain #, comma, or colon, got "${path}"`);
    }
    const result: FileRef = { path };
    if (ref.anchor !== undefined) {
      if (!ref.anchor?.trim()) {
        throw invalidFileRef("anchor must not be empty or whitespace-only");
      }
      if (/[#,]/.test(ref.anchor)) {
        throw invalidFileRef(`anchor must not contain # or comma, got "${ref.anchor}"`);
      }
      result.anchor = ref.anchor;
    }
    if (ref.startLine !== undefined || ref.endLine !== undefined) {
      if (ref.startLine === undefined || ref.endLine === undefined) {
        throw invalidFileRef("startLine and endLine must be provided together");
      }
      if (
        !Number.isInteger(ref.startLine) ||
        !Number.isInteger(ref.endLine) ||
        ref.startLine < 1 ||
        ref.endLine < ref.startLine
      ) {
        throw invalidFileRef(`invalid line range ${ref.startLine}-${ref.endLine} for "${path}"`);
      }
      result.startLine = ref.startLine;
      result.endLine = ref.endLine;
    }
    return result;
  });
}

/**
 * Validate and normalize captured code chunks before they are persisted on a
 * knowledge meta file. Structural problems throw; otherwise a shallow copy is
 * returned so callers never mutate caller-owned objects. Optional fields are
 * preserved only when defined, keeping on-disk JSON lean.
 */
export function sanitizeCodeChunks(chunks: CodeChunk[]): CodeChunk[] {
  return chunks.map((chunk) => {
    if (!chunk.path?.trim()) {
      throw invalidFileRef("code chunk path must not be empty");
    }
    if (
      !Number.isInteger(chunk.startLine) ||
      !Number.isInteger(chunk.endLine) ||
      chunk.startLine < 1 ||
      chunk.endLine < chunk.startLine
    ) {
      throw invalidFileRef(
        `code chunk for "${chunk.path}" has invalid line range ${chunk.startLine}-${chunk.endLine}`,
      );
    }
    if (typeof chunk.snippet !== "string") {
      throw invalidFileRef(`code chunk for "${chunk.path}" is missing a snippet`);
    }
    const result: CodeChunk = {
      path: chunk.path,
      startLine: chunk.startLine,
      endLine: chunk.endLine,
      snippet: chunk.snippet,
      capturedAt: chunk.capturedAt,
    };
    if (chunk.language !== undefined) result.language = chunk.language;
    if (chunk.anchor !== undefined) result.anchor = chunk.anchor;
    if (chunk.headRev !== undefined) result.headRev = chunk.headRev;
    return result;
  });
}

// ---------------------------------------------------------------------------
// Validation helpers
// ---------------------------------------------------------------------------

export function validatePlanStatus(status: string): asserts status is PlanStatus {
  if (!(PLAN_STATUSES as readonly string[]).includes(status)) {
    throw invalidPlanStatus(status);
  }
}

export function validateKnowledgeKind(kind: string): asserts kind is KnowledgeKind {
  if (!(KNOWLEDGE_KINDS as readonly string[]).includes(kind)) {
    throw invalidKnowledgeKind(kind);
  }
}

export function validateTaskStatus(status: string): asserts status is TaskStatus {
  if (!(TASK_STATUSES as readonly string[]).includes(status)) {
    throw invalidTaskStatus(status);
  }
}

export function validateTaskPriority(priority: string): asserts priority is TaskPriority {
  if (!(TASK_PRIORITIES as readonly string[]).includes(priority)) {
    throw invalidTaskPriority(priority);
  }
}

export function validateSessionStatus(status: string): asserts status is SessionStatus {
  if (!(SESSION_STATUSES as readonly string[]).includes(status)) {
    throw invalidSessionStatus(status);
  }
}

export function validateSessionRuntimeType(
  runtimeType: string,
): asserts runtimeType is SessionRuntimeType {
  if (!(SESSION_RUNTIME_TYPES as readonly string[]).includes(runtimeType)) {
    throw invalidSessionRuntimeType(runtimeType);
  }
}

export function validateSessionLinkedNodeType(
  nodeType: string,
): asserts nodeType is SessionLinkedNodeType {
  if (!(SESSION_LINKED_NODE_TYPES as readonly string[]).includes(nodeType)) {
    throw invalidSessionLink(`unknown linked node type "${nodeType}". Must be task or plan.`);
  }
}

/** A valid keyword is a non-empty, lowercase, alpha-numeric-or-dash string. */
export function sanitizeKeywords(raw: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const kw of raw) {
    const trimmed = kw.trim().toLowerCase();
    // Reject empty/blank or anything that normalizes to nothing useful
    if (!trimmed || !/[a-z0-9]/.test(trimmed)) {
      throw invalidKeyword(kw);
    }
    if (!seen.has(trimmed)) {
      seen.add(trimmed);
      out.push(trimmed);
    }
  }
  return out;
}

// ---------------------------------------------------------------------------
// Filesystem helpers
// ---------------------------------------------------------------------------

export async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

export async function ensureDir(dir: string): Promise<void> {
  await mkdir(dir, { recursive: true });
}

async function syncDirectory(filePath: string): Promise<void> {
  let handle: Awaited<ReturnType<typeof open>> | undefined;
  try {
    handle = await open(dirname(filePath), "r");
    await handle.sync();
  } catch {
    // Directory fsync is unsupported on some platforms/filesystems.
  } finally {
    await handle?.close().catch(() => {});
  }
}

/**
 * Durably replace a text file: fsync the staged file, rename atomically, then
 * fsync the parent directory where supported.
 */
export async function writeTextAtomic(filePath: string, content: string): Promise<void> {
  const tempPath = `${filePath}.${process.pid}.${randomUUID()}.tmp`;
  let handle: Awaited<ReturnType<typeof open>> | undefined;
  try {
    handle = await open(tempPath, "w");
    await handle.writeFile(content, "utf-8");
    await handle.sync();
    await handle.close();
    handle = undefined;
    await rename(tempPath, filePath);
    await syncDirectory(filePath);
  } finally {
    await handle?.close().catch(() => {});
    await rm(tempPath, { force: true }).catch(() => {});
  }
}

export interface FileMutation {
  path: string;
  /** null removes the file. */
  content: string | null;
}

/**
 * Best-effort multi-file transaction. Every file replacement is individually
 * atomic/durable; if a later mutation fails, prior files are restored from
 * their snapshots before the error is rethrown. Callers must hold the
 * collection-level advisory lock for the whole operation.
 */
export async function writeFilesTransaction(mutations: FileMutation[]): Promise<void> {
  const snapshots = await Promise.all(
    mutations.map(async (mutation) => {
      try {
        return {
          path: mutation.path,
          existed: true,
          content: await readFile(mutation.path, "utf-8"),
        };
      } catch {
        return { path: mutation.path, existed: false, content: "" };
      }
    }),
  );

  try {
    for (const mutation of mutations) {
      if (mutation.content === null) {
        await unlink(mutation.path).catch((error: unknown) => {
          if (
            !error ||
            typeof error !== "object" ||
            !("code" in error) ||
            (error as { code: string }).code !== "ENOENT"
          ) {
            throw error;
          }
        });
        await syncDirectory(mutation.path);
      } else {
        await writeTextAtomic(mutation.path, mutation.content);
      }
    }
  } catch (error) {
    for (const snapshot of snapshots) {
      if (snapshot.existed) {
        await writeTextAtomic(snapshot.path, snapshot.content).catch(() => {});
      } else {
        await unlink(snapshot.path).catch(() => {});
      }
    }
    throw error;
  }
}

export async function writeJson(filePath: string, data: unknown): Promise<void> {
  await writeTextAtomic(filePath, `${JSON.stringify(data, null, 2)}\n`);
}

export function nowISO(override?: string): string {
  return override ?? new Date().toISOString();
}

// ---------------------------------------------------------------------------
// H1 rewrite
// ---------------------------------------------------------------------------

/**
 * Build body markdown. If `content` is supplied and already starts with
 * a matching H1, use as-is. Otherwise, prepend `# title\n\n`.
 */
export function buildBody(title: string, content?: string): string {
  if (content !== undefined) {
    // If content starts with the correct H1, keep it
    if (content.startsWith(`# ${title}`)) {
      return content;
    }
    // If it starts with a different H1, replace it
    if (content.startsWith("# ")) {
      const rest = content.slice(content.indexOf("\n"));
      return `# ${title}${rest}`;
    }
    return `# ${title}\n\n${content}`;
  }
  return `# ${title}\n\n`;
}

/**
 * Rewrite the leading H1 in an existing body file.
 */
export async function rewriteH1(filePath: string, newTitle: string): Promise<void> {
  const body = await readFile(filePath, "utf-8");
  if (body.startsWith("# ")) {
    const rest = body.slice(body.indexOf("\n"));
    await writeTextAtomic(filePath, `# ${newTitle}${rest}`);
  } else {
    await writeTextAtomic(filePath, `# ${newTitle}\n\n${body}`);
  }
}
