/**
 * Session ↔ DAG linkage UI (both directions).
 *
 * `SessionLinkModal` picks a task or plan for one session (or unlinks it).
 * `LinkedSessions` is the reverse view: the sessions attached to one task/plan.
 *
 * Linkage always keys on the task/plan normalized id, never on a diagram node
 * id (T001…) — those are regenerated by `arcs diagram sort-metadata`.
 */

import { useMemo, useState } from "react";
import type { SessionLinkedNodeType, SessionMeta } from "../api/client";
import { useLinkedSessions, usePlans, useTasks, useUpdateSession } from "../api/hooks";
import { sessionLabel } from "../hooks/useSessionCandidates";
import { cx, relativeTime, truncate } from "../lib/format";
import { Badge, typeColor } from "./Badge";
import { Dialog, inputClass } from "./Dialog";
import { isVisibleSession } from "./SessionMessageForm";
import { SessionStatusBadge } from "./SessionStatusBadge";
import { useToaster } from "./Toaster";

const NODE_TYPES: SessionLinkedNodeType[] = ["task", "plan"];

interface LinkTarget {
  id: string;
  title: string;
  hint: string;
}

export function SessionLinkModal({
  slug,
  session,
  onClose,
}: {
  slug: string;
  session: SessionMeta;
  onClose: () => void;
}) {
  const { data: tasksData } = useTasks(slug);
  const { data: plansData } = usePlans(slug);
  const updateSession = useUpdateSession(slug);
  const { push } = useToaster();

  const [nodeType, setNodeType] = useState<SessionLinkedNodeType>(session.linkedNodeType ?? "task");
  const [filter, setFilter] = useState("");
  const [selectedId, setSelectedId] = useState(session.linkedNodeId ?? "");

  const targets = useMemo<LinkTarget[]>(() => {
    const list: LinkTarget[] =
      nodeType === "task"
        ? (tasksData?.tasks ?? []).map((t) => ({
            id: t.normalizedId,
            title: t.title,
            hint: t.status,
          }))
        : (plansData?.plans ?? []).map((p) => ({
            id: p.normalizedId,
            title: p.title,
            hint: p.status,
          }));
    const q = filter.trim().toLowerCase();
    if (!q) return list;
    return list.filter((t) => t.title.toLowerCase().includes(q) || t.id.includes(q));
  }, [nodeType, tasksData, plansData, filter]);

  const onError = (err: unknown) => push("error", err instanceof Error ? err.message : String(err));

  const submit = () => {
    if (!selectedId) return;
    updateSession.mutate(
      { id: session.normalizedId, input: { linkedNodeType: nodeType, linkedNodeId: selectedId } },
      {
        onSuccess: () => {
          push("success", `session linked to ${nodeType}`);
          onClose();
        },
        onError,
      },
    );
  };

  const unlink = () => {
    updateSession.mutate(
      { id: session.normalizedId, input: { linkedNodeType: null, linkedNodeId: null } },
      {
        onSuccess: () => {
          push("success", "session unlinked");
          onClose();
        },
        onError,
      },
    );
  };

  return (
    <Dialog
      title={`link session — ${truncate(session.runtimeSessionId, 24)}`}
      onClose={onClose}
      width="max-w-2xl"
    >
      <div className="mb-2 flex items-center gap-1 text-[11px]">
        {NODE_TYPES.map((t) => (
          <button
            key={t}
            type="button"
            onClick={() => {
              setNodeType(t);
              setSelectedId(session.linkedNodeType === t ? (session.linkedNodeId ?? "") : "");
            }}
            className={cx(
              "px-1.5 py-0.5",
              nodeType === t
                ? "bg-term-green font-bold text-term-bg"
                : "text-term-dim hover:text-term-fg",
            )}
          >
            {t}
          </button>
        ))}
        <span className="flex-1" />
        {session.linkedNodeId && (
          <span className="text-term-dim">
            currently: <span className="text-term-amber">{session.linkedNodeType}</span> ·{" "}
            <span className="text-term-fg">{truncate(session.linkedNodeId, 32)}</span>
          </span>
        )}
      </div>

      <input
        type="text"
        value={filter}
        onChange={(e) => setFilter(e.target.value)}
        placeholder={`filter ${nodeType}s…`}
        className={inputClass}
      />

      <div className="mt-2 max-h-64 overflow-y-auto border border-term-border">
        {targets.length === 0 ? (
          <div className="px-2 py-4 text-center text-[12px] text-term-dim">
            <span className="text-term-border-hi">∅</span> no {nodeType}s match
          </div>
        ) : (
          targets.map((t) => (
            <button
              key={t.id}
              type="button"
              onClick={() => setSelectedId(t.id)}
              onDoubleClick={submit}
              className={cx(
                "flex w-full items-center gap-2 border-b border-term-border/40 px-2 py-1 text-left text-[12px]",
                selectedId === t.id
                  ? "bg-term-green text-term-bg"
                  : "text-term-fg hover:bg-term-fg/5",
              )}
            >
              <span className="w-3 text-term-green">{selectedId === t.id ? "▸" : ""}</span>
              <span className="flex-1 truncate">{t.title}</span>
              <span
                className={cx(
                  "text-[11px]",
                  selectedId === t.id ? "text-term-bg" : "text-term-dim",
                )}
              >
                {t.hint}
              </span>
            </button>
          ))
        )}
      </div>

      <div className="mt-3 flex items-center gap-2 text-[12px]">
        <button
          type="button"
          disabled={!selectedId || updateSession.isPending}
          onClick={submit}
          className="border border-term-green/60 px-2 py-0.5 font-bold text-term-green hover:bg-term-green hover:text-term-bg disabled:opacity-50"
        >
          {updateSession.isPending ? "…" : "link"}
        </button>
        {session.linkedNodeId && (
          <button
            type="button"
            disabled={updateSession.isPending}
            onClick={unlink}
            className="border border-term-red/60 px-2 py-0.5 text-term-red hover:bg-term-red hover:text-term-bg disabled:opacity-50"
          >
            unlink
          </button>
        )}
        <button
          type="button"
          onClick={onClose}
          className="border border-term-border px-2 py-0.5 text-term-dim hover:text-term-fg"
        >
          cancel
        </button>
      </div>
    </Dialog>
  );
}

/**
 * Sessions linked to one task/plan. Renders nothing when empty, mirroring the
 * conditional "source files" block on plan detail — including when every linked
 * session belongs to a runtime the UI hides (`isVisibleSession`).
 */
export function LinkedSessions({
  slug,
  nodeType,
  nodeId,
}: {
  slug: string;
  nodeType: SessionLinkedNodeType;
  nodeId: string;
}) {
  const { data } = useLinkedSessions(slug, nodeType, nodeId);
  const sessions = (data ?? []).filter(isVisibleSession);
  if (sessions.length === 0) return null;

  return (
    <div className="mb-4 border border-term-border">
      <div className="flex items-center gap-2 border-b border-term-border bg-term-panel px-2 py-1 text-[11px] tracking-wide text-term-dim uppercase">
        linked sessions
        <Badge color={typeColor(nodeType)}>{nodeType}</Badge>
        <span className="flex-1" />
        <span className="normal-case">{sessions.length}</span>
      </div>
      <ul className="divide-y divide-term-border/40">
        {sessions.map((s) => (
          <li key={s.normalizedId} className="flex items-center gap-2 px-2 py-1 text-[12px]">
            <SessionStatusBadge status={s.status} />
            <span className="font-bold">{sessionLabel(s)}</span>
            <span className="text-term-dim">{truncate(s.runtimeSessionId, 20)}</span>
            <span className="flex-1" />
            <span className="text-term-dim">{relativeTime(s.lastMessageAt ?? s.updatedAt)}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
